version: '2'
services:
    rspamd:
        build: ./rspamd
        image: seti/mailstack-rspamd
    dovecot:
        build: ./dovecot
        image: seti/mailstack-dovecot
        container_name: mailstack-dovecot
    postfix:
        build: ./postfix
        image: seti/mailstack-postfix
        container_name: mailstack-postfix
    automx:
        build: ./automx
        image: seti/mailstack-automx
        container_name: mailstack-automx
